recipes = {
    "spaghetti_carbonara": "Cook spaghetti. Mix eggs, parmesan, pancetta, and black pepper. Combine with hot pasta.",
    "sushi_roll": "Roll sushi rice and fish/veggies in seaweed. Slice and serve with soy sauce.",
    "tacos": "Fill tortillas with spiced meat, veggies, and cheese. Serve with salsa and guacamole.",
    "quesadilla": "Stuff tortillas with cheese and optional fillings. Grill until cheese melts.",
    "risotto": "Cook Arborio rice with broth, onions, white wine, and parmesan cheese.",
    "french_onion_soup": "Caramelize onions. Simmer in beef broth and top with toasted bread and melted cheese.",
    "ratatouille": "Layer sliced vegetables with tomato sauce and bake.",
    "croissant": "Layer butter in dough and fold repeatedly. Bake until flaky.",
    "beef_wellington": "Wrap beef fillet with mushroom duxelles and puff pastry. Bake until golden.",
    "paella": "Cook rice with seafood, chicken, and saffron in a large shallow pan.",
    "falafel": "Deep fry balls of ground chickpeas, herbs, and spices. Serve with pita bread.",
    "hummus": "Blend chickpeas, tahini, olive oil, garlic, and lemon juice.",
    "shawarma": "Grill spiced meat and wrap it in pita bread with veggies and sauce.",
    "gyros": "Wrap grilled meat, tomatoes, onions, and tzatziki in pita bread.",
    "pierogi": "Stuff dumplings with potato, cheese, or meat. Boil and sauté in butter.",
    "borscht": "Beet soup with vegetables and a dollop of sour cream.",
    "goulash": "Slow-cooked stew of beef, paprika, and vegetables.",
    "baklava": "Layer phyllo dough with nuts and honey. Bake until golden.",
    "crepes": "Thin pancakes filled with sweet or savory fillings.",
    "churros": "Deep fry dough sticks. Coat with sugar and cinnamon. Serve with chocolate sauce.",
    "mojito_chicken": "Marinate chicken with lime, mint, and garlic. Grill until done.",
    "clam_chowder": "Creamy soup made with clams, potatoes, onions, and celery.",
    "pho": "Vietnamese noodle soup with beef or chicken and herbs.",
    "bibimbap": "Korean rice bowl topped with meat, veggies, and fried egg.",
    "pad_thai": "Thai stir-fried noodles with shrimp, tofu, peanuts, and lime.",
    "green_curry": "Thai curry with coconut milk, green chili, chicken, and vegetables.",
    "pavlova": "Meringue dessert topped with whipped cream and fresh fruits.",
    "bruschetta": "Grilled bread topped with tomatoes, garlic, basil, and olive oil.",
    "gnocchi": "Soft potato dumplings cooked with butter and sage or tomato sauce.",
    "cheesecake": "Creamy dessert with a graham cracker crust and sweet cheese filling.",
    "ramen": "Japanese noodle soup with broth, toppings like egg, and meat or veggies.",
    "tempura": "Lightly batter and deep-fry seafood and vegetables.",
    "souvlaki": "Grilled meat skewers served with pita bread and tzatziki sauce.",
    "tiramisu": "Layer coffee-soaked ladyfingers with mascarpone cream and cocoa.",
    "banoffee_pie": "Dessert with bananas, cream, toffee, and biscuit base.",
    "moussaka": "Layered casserole with eggplant, ground meat, and béchamel sauce.",
    "fajitas": "Sauté meat and veggies. Serve with tortillas and toppings.",
    "macarons": "Colorful almond meringue cookies with creamy filling.",
    "spring_rolls": "Fill rice paper with veggies or meat and roll tightly.",
    "dim_sum": "Small bite-sized dumplings filled with meat or vegetables.",
    "stuffed_peppers": "Bell peppers stuffed with rice, meat, and tomato sauce. Bake until tender.",
    "currywurst": "German sausage topped with spiced ketchup and curry powder.",
    "wonton_soup": "Broth with dumplings filled with ground pork or shrimp.",
    "caesar_salad": "Romaine lettuce tossed with Caesar dressing, croutons, and parmesan.",
    "chicken_parmesan": "Breaded chicken breast baked with tomato sauce and mozzarella.",

    "burger": "Grill beef patties. Assemble with buns, cheese, lettuce, and condiments.",
    "hot_dog": "Serve grilled sausages in a bun with mustard, ketchup, and toppings.",
    "nachos": "Layer tortilla chips with cheese, jalapeños, and toppings. Bake until melted.",
    "fries": "Deep-fry thin potato strips. Season with salt.",
    "onion_rings": "Dip onion slices in batter and deep fry.",
    "popcorn_chicken": "Coat chicken pieces in batter and deep fry.",
    "potato_wedges": "Bake or fry potato wedges with seasoning.",
    "corn_dogs": "Coat hot dogs in cornmeal batter and deep fry.",
    "pizza_pockets": "Stuff dough with pizza toppings. Bake or fry.",
    "garlic_bread": "Spread butter, garlic, and herbs on bread. Toast or bake.",
    "mozzarella_sticks": "Bread mozzarella sticks and fry until crispy.",
    "donuts": "Fry sweet dough rings and glaze with icing.",
    "sliders": "Small burgers with different fillings like pulled pork or crispy chicken.",
    "queso_dip": "Melt cheese with tomatoes and chilies. Serve with tortilla chips.",
    "potato_chips": "Thinly slice potatoes. Deep fry until crispy.",
    "chicken_nuggets": "Bread chicken pieces and deep fry until golden.",
    "pretzels": "Boil and bake dough twists. Sprinkle with salt.",
    "cheese_puffs": "Bake or fry dough made with cheese.",
    "jalapeno_poppers": "Stuff jalapeños with cheese. Coat and fry.",
    "tater_tots": "Shredded potatoes shaped and fried into small cylinders.",
    "funnel_cake": "Pour batter through a funnel into hot oil. Fry and dust with powdered sugar.",
    "bagel_bites": "Mini bagels topped with pizza sauce, cheese, and toppings.",
    "soft_pretzels": "Boil dough, sprinkle with salt, and bake.",
    "chocolate_chip_cookies": "Mix butter, sugar, eggs, and chocolate chips. Bake until golden.",
    "brownies": "Mix cocoa, sugar, butter, and eggs. Bake until fudgy.",
    "cupcakes": "Bake individual small cakes and frost with icing.",
    "ice_cream_sundae": "Layer ice cream with sauces, nuts, and whipped cream.",
    "milkshake": "Blend ice cream with milk and flavoring. Top with whipped cream.",
    "candy_floss": "Spin sugar into fluffy, colorful threads.",
    "poutine": "Fries topped with cheese curds and gravy.",
    "chicken_wings": "Deep-fry wings and coat with buffalo or barbecue sauce.",
    "loaded_fries": "Top fries with cheese, bacon, and jalapeños.",
    "stuffed_crust_pizza": "Pizza with cheese stuffed into the crust.",
    "butter_chicken": "Marinate chicken in yogurt and spices. Cook with butter, cream, and tomato gravy. Serve with naan.",
    "paneer_butter_masala": "Cook paneer in a rich tomato and butter-based gravy with cream.",
    "biryani": "Layer marinated chicken/mutton with half-cooked rice. Cook on low flame with saffron and fried onions.",
    "dal_tadka": "Boil lentils. Temper with ghee, cumin, garlic, and chilies.",
    "aloo_paratha": "Stuff spiced mashed potatoes in dough. Roll and cook with ghee on a griddle.",
    "samosa": "Stuff spiced potato filling in dough cones. Deep fry until golden.",
    "chole": "Cook chickpeas with onion, tomatoes, and spices. Serve with bhatura.",
    "rajma": "Cook kidney beans with onion-tomato gravy. Serve with rice.",
    "palak_paneer": "Blend cooked spinach and spices. Add paneer cubes and simmer.",
    "pav_bhaji": "Cook mixed vegetables with spices. Mash and serve with buttered bread.",
    "dosa": "Fermented rice and lentil batter cooked thin on a griddle.",
    "idli": "Steam fermented rice and lentil batter in molds.",
    "sambar": "Cook lentils with tamarind, vegetables, and spices.",
    "vada": "Deep-fry lentil batter shaped into doughnuts.",
    "poha": "Flattened rice cooked with onions, mustard seeds, and curry leaves.",
    "upma": "Semolina cooked with vegetables and seasoned with mustard seeds.",
    "puri": "Deep-fry rolled-out dough and serve with potato curry.",
    "kheer": "Cook rice in milk with sugar, cardamom, and nuts.",
    "gulab_jamun": "Fry milk-solid balls and soak them in sugar syrup.",
    "jalebi": "Fry fermented batter in loops and soak in sugar syrup.",
    "ladoo": "Roast and shape flour or lentils with sugar and ghee into balls.",
    "halwa": "Cook semolina or carrots with sugar, ghee, and milk.",
    "malai_kofta": "Fry paneer and potato balls. Serve with creamy tomato gravy.",
    "kadhi": "Yogurt-based curry with gram flour and pakoras.",
    "thepla": "Spiced flatbread made with wheat flour, fenugreek, and yogurt.",
    "bhindi_masala": "Stir-fried okra with onions, tomatoes, and spices.",
    "aloo_gobi": "Cook cauliflower and potatoes with spices.",
    "masala_dosa": "Stuff dosa with a spiced potato filling.",
    "veg_pulao": "Cook rice with vegetables, whole spices, and herbs.",
    "fish_curry": "Cook fish in coconut milk with spices.",
    "mutton_rogan_josh": "Slow-cooked mutton in a yogurt-based gravy.",
    "paneer_tikka": "Grill marinated paneer cubes with spices.",
    "kachori": "Stuff fried dough with spiced lentil filling.",
    "pakora": "Deep-fry spiced gram flour-coated vegetables.",
    "sheer_korma": "Vermicelli cooked with milk, sugar, nuts, and dates.",
    "paneer_bhurji": "Scrambled paneer cooked with onions, tomatoes, and spices.",
    "veg_korma": "Mixed vegetables cooked in a creamy coconut and spice gravy.",
    "khichdi": "Cook rice and lentils together with turmeric and ghee.",
    "baingan_bharta": "Chargrill eggplant, mash, and cook with onions and spices.",
    "misal_pav": "Spicy sprouted lentils served with buttered bread.",
    "thalipeeth": "Multi-grain spiced flatbread cooked on a griddle.",
    "shrikhand": "Strained yogurt mixed with sugar, saffron, and cardamom.",
    "rasgulla": "Boil cheese balls in sugar syrup.",
    "dhokla": "Steam fermented gram flour batter and temper with mustard seeds.",
    "modak": "Sweet dumplings filled with coconut and jaggery.",
    "lassi": "Blend yogurt with sugar, water, and cardamom.",
    "chaat": "Mix fried dough, boiled potatoes, yogurt, and tamarind chutney.",
    "tandoori_chicken": "Marinate chicken with yogurt and spices. Grill or bake.",
    "beef_curry": "Cook beef with coconut milk and traditional spices.",
    "rava_dosa": "Instant dosa made with semolina, rice flour, and spices.",
    "butter_naan": "Flatbread cooked in a tandoor with butter on top.",
    "shahi_paneer": "Paneer cooked in a creamy, cashew-based gravy.",
    "veg_manchurian": "Deep-fried veggie balls in spicy soy-based gravy.",
    "gobi_manchurian": "Cauliflower florets fried and tossed in a tangy sauce.",
    "tamarind_rice": "Rice cooked with tamarind pulp, peanuts, and spices.",
    "mango_pickle": "Spiced mango pieces preserved in oil.",
    "puran_poli": "Sweet stuffed flatbread made with lentils and jaggery.",
    "rasmalai": "Flattened cheese balls soaked in saffron-flavored milk.",
    "kachumber_salad": "Fresh cucumber, tomato, and onion salad with lemon juice.",
    "payasam": "Sweet pudding made with milk, rice, and cardamom.",
    "gajar_ka_halwa": "Carrots cooked with milk, ghee, and sugar.",
    "veg_cutlet": "Deep-fry patties made of mashed vegetables and spices.",
    "kathi_roll": "Wrap stuffed with paneer, chicken, or veggies."
}

# Add more international recipes to make it to 100 if required!
calorie_database = {
    # Indian Foods
    "roti": 120,
    "rice": 206,
    "dal": 120,
    "sambar": 150,
    "idli": 58,
    "dosa": 133,
    "poha": 180,
    "biryani": 292,
    "paneer butter masala": 350,
    "butter chicken": 490,
    "chole bhature": 450,
    "aloo paratha": 210,
    "rajma chawal": 220,
    "kheer": 150,
    "pulao": 230,
    "upma": 180,
    "medu vada": 100,
    "gulab jamun": 140,
    "jalebi": 150,
    "samosa": 150,
    "pakora": 120,
    "pav bhaji": 400,
    "vada pav": 300,
    "sev puri": 150,
    "pani puri": 150,
    "khaman dhokla": 80,
    "thepla": 120,
    "sarson ka saag": 100,
    "makki di roti": 150,
    "malai kofta": 300,
    "fish curry": 200,
    "mutton curry": 300,
    "tandoori chicken": 250,
    "naan": 270,
    "kulcha": 150,
    "lassi": 250,
    "halwa": 200,
    "bhindi masala": 120,
    "aloo gobi": 150,
    "kadhi pakora": 200,

    # Global Foods
    "pasta": 300,
    "pizza": 400,
    "burger": 300,
    "sandwich": 250,
    "fried chicken": 450,
    "french fries": 312,
    "hot dog": 150,
    "steak": 271,
    "bacon": 42,
    "cheese": 113,
    "omelette": 154,
    "scrambled eggs": 91,
    "toast": 75,

    # Desserts
    "chocolate": 546,
    "ice cream": 137,
    "brownie": 132,
    "cake": 350,
    "donut": 195,
    "cookies": 75,

    # Snacks
    "popcorn": 382,
    "chips": 536,
    "nachos": 313,
    "pretzels": 380,
    "trail mix": 607,
    "energy bar": 250,

    # Beverages
    "black coffee": 2,
    "tea": 47,
    "soda": 150,
    "orange juice": 110,
    "milk": 42,
    "protein shake": 200,
    "beer": 154,
    "wine": 125,

    # Miscellaneous
    "honey": 64,
    "peanut butter": 588,
    "jam": 56,
    "butter": 717,
    "olive oil": 884,
    "almonds": 576,
    "cashews": 553,
    "walnuts": 654,
    "bread": 75,
    "chapati": 120,
    "pancakes": 227
}